version: '3.8'
services:

  mariadb:
    extends:
      file: dockerfiles/mariadb/docker-compose.yml
      service: mariadb

  mongodb:
    extends:
      file: dockerfiles/mongodb/docker-compose.yml
      service: mongodb

  nginx:
    extends:
      file: dockerfiles/nginx/docker-compose.yml
      service: nginx

  node:
    extends:
      file: dockerfiles/node/docker-compose.yml
      service: node

  php:
    extends:
      file: dockerfiles/php/docker-compose.yml
      service: php

  postgres:
    extends:
      file: dockerfiles/postgres/docker-compose.yml
      service: postgres

  rabbitmq:
    extends:
      file: dockerfiles/rabbitmq/docker-compose.yml
      service: rabbitmq

  redis:
    extends:
      file: dockerfiles/redis/docker-compose.yml
      service: redis

networks:
  skelark-network:
    driver: bridge