version: '3.8'
services:

  nginx:
    extends:
      file: nginx.docker-compose.yml
      service: nginx

  node:
    extends:
      file: node.docker-compose.yml
      service: node

  php:
    extends:
      file: php.docker-compose.yml
      service: php

  mariadb:
    extends:
      file: mariadb.docker-compose.yml
      service: mariadb

  postgres:
    extends:
      file: postgres.docker-compose.yml
      service: postgres

  mongodb:
    extends:
      file: mongodb.docker-compose.yml
      service: mongodb

  rabbitmq:
    extends:
      file: rabbitmq.docker-compose.yml
      service: rabbitmq

  redis:
    extends:
      file: redis.docker-compose.yml
      service: redis

networks:
  skelark-network:
    driver: bridge