version: '3.8'
services:

  mongodb:
    container_name: skelark-mongodb
    build: 
      context: ./
      dockerfile: dockerfiles/mongodb/Dockerfile
    tty: true
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    working_dir: /data/db
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - skelark-network