version: '3.8'
services:

  mariadb:
    container_name: skelark-mariadb
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    working_dir: /var/lib/mysql
    volumes:
      - ../../data/mariadb:/var/lib/mysql/
      # - ../../mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - skelark-network