version: '3.8'
services:

  postgres:
    container_name: skelark-postgres
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    working_dir: /var/lib/postgresql/data
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
    networks:
      - skelark-network